# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: resultproxy
  namespace: vote
##  annotations:
##    ingress.kubernetes.io/rewrite-target: /
##    ingress.kubernetes.io/force-ssl-redirect: "false"
##    kubernetes.io/ingress.allow-http: "true"
spec:
  virtualhost:
    fqdn: e890lectresult.gov.lab
  routes:
    - conditions:
      - prefix: /
      services:
        - name: result
          port: 5001
